### ISSUE TITLE
Implement Document Similarity Engine

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/document-compass#2]
**Title:** Create Core Document Similarity Detection System
**Priority:** High  
**Type:** Feature Implementation  
**Estimated Time:** 3-4 days

### Description
Implement the core document similarity engine using sentence transformers and FAISS for efficient similarity search.

### Tasks
- [ ] Set up Python backend environment with FastAPI
- [ ] Implement document vectorization:
  ```python
  class DocumentVectorizer:
      def __init__(self):
          self.model = SentenceTransformer('all-MiniLM-L6-v2')
          self.file_processors = {
              'pdf': PDFProcessor(),
              'ppt': PPTProcessor(),
              'jpg': ImageProcessor(),
          }
  ```
- [ ] Create FAISS index implementation
- [ ] Build document clustering system
- [ ] Implement similarity threshold configuration
- [ ] Add background processing for large documents
- [ ] Create API endpoints for similarity search
- [ ] Implement caching system for vectors

### Acceptance Criteria
- ✅ Can process PDF, PPT, and JPG files
- ✅ Similarity search completes in <2 seconds for 1000 documents
- ✅ API endpoints properly documented with OpenAPI
- ✅ Proper error handling for corrupt/invalid files
- ✅ Caching system reduces repeated processing
- ✅ Unit tests achieve 80%+ coverage
